/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./MarketplaceV2.types";
import * as _1 from "./MarketplaceV2.client";
import * as _2 from "./MarketplaceV2.message-composer";
import * as _3 from "./MarketplaceV2.react-query";
export namespace contracts {
  export const MarketplaceV2 = { ..._0,
    ..._1,
    ..._2,
    ..._3
  };
}